name: Build gbs-control firmware

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jeffbrl/gbsc-builder:${{ github.sha }}

    - name: Build gbsc firmware
      run: mkdir output && docker run -v ./output:/app/output jeffbrl/gbsc-builder:${{ github.sha }}

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: gbs-control.ino.bin
        path: ./output
