name: Build gbs-control firmware

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      CONTAINER_TAG: v0.1

    steps:

    - name: Build gbsc firmware
      run: docker run -v /home/runner/work:/app/output jeffbrl/gbsc-builder:$CONTAINER_TAG

    - name: Show dir contents
      run: ls -la /home/runner/work

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: gbsc_firmware
        path: gbs-control.ino.bin
