name: Build gbs-control firmware

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  containerbuild:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jeffbrl/gbsc-builder:$(date +%s)

  firmwarebuild:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build gbsc firmware
      run: docker run -v /tmp:/app/output jeffbrl/gbsc-builder:$(date +%s)

