name: Build gbs-control firmware

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: /home/runner/work/output
      CONTAINER_TAG: v0.1

    steps:

    - name: Build gbsc firmware
      run: mkdir $OUTPUT_DIR && docker run -v $OUTPUT_DIR:/app/output jeffbrl/gbsc-builder:$CONTAINER_TAG

    - name: Show dir contents
      run: ls -la $OUTPUT_DIR

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: gbsc_firmware
        path: $OUTPUT_DIR/gbs-control.ino.bin
